/**
 * Boots the real Bullpane server (apps/server, through tsx, exactly as
 * `pnpm dev` does) on a free port with a throwaway SQLite data dir, and gives a
 * cookie-carrying HTTP client for its API.
 *
 * Pro: a throwaway Ed25519 keypair signs a Pro license on the spot and the
 * server is told to trust that public key (LICENSE_PUBLIC_KEY_B64), so the
 * smoke can exercise every Pro feature without the vendor's private key.
 */
import { spawn, type ChildProcess } from "node:child_process";
import { generateKeyPairSync, sign } from "node:crypto";
import { mkdtempSync, rmSync, existsSync } from "node:fs";
import { createServer } from "node:net";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { waitFor } from "./harness.js";

export const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");

async function freePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const srv = createServer();
    srv.listen(0, "127.0.0.1", () => {
      const port = (srv.address() as { port: number }).port;
      srv.close(() => resolve(port));
    });
    srv.on("error", reject);
  });
}

/**
 * Same wire format as apps/server/src/license.ts signLicense():
 * base64url(JSON payload) + "." + base64url(Ed25519 signature over the payload part).
 */
function throwawayProLicense(): { key: string; publicKeyB64: string } {
  const { privateKey, publicKey } = generateKeyPairSync("ed25519");
  const payload = {
    licensee: "Bullpane smoke test",
    email: "smoke@example.com",
    plan: "pro",
    issuedAt: Date.now(),
    expiresAt: Date.now() + 3_600_000,
    notes: "throwaway key generated by apps/smoke",
  };
  const body = Buffer.from(JSON.stringify(payload)).toString("base64url");
  const signature = sign(null, Buffer.from(body), privateKey).toString("base64url");
  return {
    key: `${body}.${signature}`,
    publicKeyB64: publicKey.export({ type: "spki", format: "der" }).toString("base64"),
  };
}

export interface RunningServer {
  url: string;
  pro: boolean;
  log: () => string;
  stop: () => Promise<void>;
}

export async function startServer(opts: { pro: boolean; env?: Record<string, string> }): Promise<RunningServer> {
  const port = await freePort();
  const dataDir = mkdtempSync(path.join(tmpdir(), "bullpane-smoke-"));
  const webDist = path.join(REPO_ROOT, "apps/web/dist");
  const env: Record<string, string> = {
    ...(process.env as Record<string, string>),
    PORT: String(port),
    HOST: "127.0.0.1",
    PUBLIC_URL: `http://127.0.0.1:${port}`,
    BULLPANE_DATA_DIR: dataDir,
    SESSION_SECRET: "smoke-test-session-secret-0123456789abcdef",
    // the alerts engine must tick fast enough for the smoke to see an alert fire
    BULLPANE_ALERTS_INTERVAL: "1",
    ...(existsSync(path.join(webDist, "index.html")) ? { WEB_DIST: webDist } : {}),
    ...opts.env,
  };
  delete env.DATABASE_URL;
  delete env.BULLPANE_CONNECTIONS;
  delete env.DEMO_MODE;
  if (opts.pro) {
    const lic = throwawayProLicense();
    env.BULLPANE_LICENSE_KEY = lic.key;
    env.LICENSE_PUBLIC_KEY_B64 = lic.publicKeyB64;
  } else {
    delete env.BULLPANE_LICENSE_KEY;
  }

  let output = "";
  const child: ChildProcess = spawn(path.join(REPO_ROOT, "node_modules/.bin/tsx"), ["src/index.ts"], {
    cwd: path.join(REPO_ROOT, "apps/server"),
    env,
    stdio: ["ignore", "pipe", "pipe"],
  });
  child.stdout?.on("data", (d) => (output += d));
  child.stderr?.on("data", (d) => (output += d));

  const url = `http://127.0.0.1:${port}`;
  await waitFor(
    "the server to answer /api/health",
    async () => {
      if (child.exitCode !== null) throw new Error(`server exited (${child.exitCode}):\n${output.slice(-2000)}`);
      const res = await fetch(`${url}/api/health`).catch(() => null);
      return res?.ok ?? false;
    },
    60_000,
    250,
  );

  return {
    url,
    pro: opts.pro,
    log: () => output,
    stop: async () => {
      if (child.exitCode === null) {
        child.kill("SIGTERM");
        await waitFor("the server to exit", async () => child.exitCode !== null, 10_000).catch(() => child.kill("SIGKILL"));
      }
      rmSync(dataDir, { recursive: true, force: true });
    },
  };
}

export class HttpError extends Error {
  constructor(
    readonly status: number,
    readonly body: unknown,
    method: string,
    route: string,
  ) {
    super(`${method} ${route} → ${status} ${typeof body === "string" ? body : JSON.stringify(body)}`.slice(0, 600));
  }
}

/** A browser-like API client: JSON in and out, and the session cookie carried across calls. */
export class Api {
  private cookie = "";
  constructor(readonly base: string) {}

  async request<T = unknown>(method: string, route: string, body?: unknown): Promise<{ status: number; body: T }> {
    const headers: Record<string, string> = { accept: "application/json" };
    if (body !== undefined) headers["content-type"] = "application/json";
    if (this.cookie) headers.cookie = this.cookie;
    const res = await fetch(`${this.base}/api${route}`, { method, headers, body: body === undefined ? undefined : JSON.stringify(body) });
    const setCookie = res.headers.getSetCookie?.() ?? [];
    if (setCookie.length) this.cookie = setCookie.map((c) => c.split(";")[0]).join("; ");
    const text = await res.text();
    let parsed: unknown = text;
    try {
      parsed = text ? JSON.parse(text) : null;
    } catch {
      /* not JSON */
    }
    return { status: res.status, body: parsed as T };
  }

  /** Throws unless the status is 2xx. */
  async ok<T = unknown>(method: string, route: string, body?: unknown): Promise<T> {
    const res = await this.request<T>(method, route, body);
    if (res.status < 200 || res.status >= 300) throw new HttpError(res.status, res.body, method, route);
    return res.body;
  }

  get = <T = unknown>(route: string) => this.ok<T>("GET", route);
  post = <T = unknown>(route: string, body: unknown = {}) => this.ok<T>("POST", route, body);
  patch = <T = unknown>(route: string, body: unknown) => this.ok<T>("PATCH", route, body);
  put = <T = unknown>(route: string, body: unknown) => this.ok<T>("PUT", route, body);
  del = <T = unknown>(route: string) => this.ok<T>("DELETE", route);

  /** Expects exactly this status; returns the body. */
  async expect(status: number, method: string, route: string, body?: unknown): Promise<unknown> {
    const res = await this.request(method, route, body);
    if (res.status !== status) throw new HttpError(res.status, res.body, method, `${route} (expected ${status})`);
    return res.body;
  }
}
